/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class polyglot_model_HelloJNI */

#ifndef _Included_polyglot_model_HelloJNI
#define _Included_polyglot_model_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     polyglot_model_HelloJNI
 * Method:    calculateInC
 * Signature: (IDIDI)D
 */
JNIEXPORT jdouble JNICALL Java_polyglot_model_HelloJNI_calculateInC
  (JNIEnv *, jobject, jint, jdouble, jint, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
